version: '3'
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat-app
      MYSQL_USER: thibaut
      MYSQL_PASSWORD: password
    volumes:
      - mysql-volume-container:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - chat-network

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    networks:
      - chat-network

networks:
  chat-network:

volumes:
  mysql-volume-container: